# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
services:
    # default configuration for services in *this* file
    _defaults:
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    GollumSF\ControllerActionExtractorBundle\Extractor\ControllerActionExtractorInterface:
        class: GollumSF\ControllerActionExtractorBundle\Extractor\ControllerActionExtractor
        arguments:
            - '@service_container'
        
